
# for ltx.py
[LaTeX]
compiler = lualatex.exe
; compiler = xelatex.exe

# for iu.py
[ImageMagick]
path = C:\Program Files\ImageMagick-7.0.9-Q16\magick.exe
[Inkscape]
path = C:\Program Files\Inkscape\inkscape.com

# for tlconf.py
[TeX Live]
texmflocal = C:\texlive\texmf-local\tex\latex\local
repository = http://mirror.navercorp.com/CTAN/systems/texlive/tlnet
TEXEDIT = \"C:\Users\yihoze\AppData\Local\Programs\Microsoft VS Code\code.exe\" -r -g \"%s\":%d
TEXMFHOME = C:\home\texmf

[TEXMF.CNF]
path =  C:\texlive\2020\texmf.cnf
target = $SystemRoot/fonts//
substitute = $SystemRoot/fonts;$localappdata/Microsoft/Windows/Fonts//

[LOCAL.CONF]
path = C:\texlive\2020\texmf-var\fonts\conf\local.conf
content = <dir>C:/Users/yihoze/AppData/Local/Microsoft/Windows/Fonts</dir>

[SumatraPDF]
path = C:\Program Files\SumatraPDF\SumatraPDF.exe
inverse-search = "C:\Users\yihoze\AppData\Local\Programs\Microsoft VS Code\code.exe" -r -g "%f":%l

[Sphinx Style]
latex = hzguide.cls, hzdissuade.sty, hzsphinx.sty, hzjupyter.sty

# for open.py
[Text Editor]
path = C:\Users\yihoze\AppData\Local\Programs\Microsoft VS Code\code.exe
associations = .aux, .bib, .bst, .cls, .cnf, .conf, .cmd, .css, .csv, .gv, .ini, .ind, .idx, .ist, .ipynb, .list, .lof, .log, .lot, .md, .ps1, .py, .rst, .sty, .tex, .tmp, .toc, .tsv, .txt

[Adobe Reader]
path = C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe

# for nb2pdf.py
[Jupyter Template]
latex = nb2pdf.tplx

# To add other repositories and use KTUG's private repository:
#> tlmgr option repository  http://mirror.navercorp.com/CTAN/systems/texlive/tlnet
#> tlmgr option repository http://mirror.kakao.com/CTAN/systems/texlive/tlnet/
#> tlmgr option repository https://cran.asia/tex/systems/texlive/tlnet/
#> tlmgr repository add http://ftp.ktug.org/KTUG/texlive/tlnet ktug
#> tlmgr pinning add ktug *
#> tlmgr repository add  https://cran.asia/KTUG/texlive/ cranasia
#> tlmgr pinning add cranasia "*"
#> tlmgr repository list